
/*
 * purpose: outline all purposes of data sent
 */

public enum Packet{
    PLAYER_POS,
    PLAYER_STATUS,
    WAITING_PLAYERS,
    GAME_STATE_CHANGE,
    PLAYER_SPAWN_INDEX,
    DISCONNECTED_PLAYER,
    IS_IN_BOSS_ROOM,
    BOSS_ATTACK_START,
    BOSS_ATTACK_END,
    DAMAGE_TO_BOSS,
    BOSS_HEALTH,
    BOSS_MAX_HEALTH,
    HASHMAP_POSITIONS,
    PLAYER_COLOR,
    BOSS_INVULNERABLE,
    BOSS_QUOTE,
    GAME_END,
    PLAYER_PROJECTILE,
    RESTART_GAME,
    PLAYER_HEALED,
    SPAWN_HEART,
    TRANSFORM_BOSS,
}
